
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `empleado` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model empleado
 * 
 */
export type empleadoModel = runtime.Types.Result.DefaultSelection<Prisma.$empleadoPayload>

export type AggregateEmpleado = {
  _count: EmpleadoCountAggregateOutputType | null
  _avg: EmpleadoAvgAggregateOutputType | null
  _sum: EmpleadoSumAggregateOutputType | null
  _min: EmpleadoMinAggregateOutputType | null
  _max: EmpleadoMaxAggregateOutputType | null
}

export type EmpleadoAvgAggregateOutputType = {
  id: number | null
  id_empresa: number | null
}

export type EmpleadoSumAggregateOutputType = {
  id: number | null
  id_empresa: number | null
}

export type EmpleadoMinAggregateOutputType = {
  id: number | null
  nombre: string | null
  id_empresa: number | null
  apellido: string | null
}

export type EmpleadoMaxAggregateOutputType = {
  id: number | null
  nombre: string | null
  id_empresa: number | null
  apellido: string | null
}

export type EmpleadoCountAggregateOutputType = {
  id: number
  nombre: number
  id_empresa: number
  apellido: number
  _all: number
}


export type EmpleadoAvgAggregateInputType = {
  id?: true
  id_empresa?: true
}

export type EmpleadoSumAggregateInputType = {
  id?: true
  id_empresa?: true
}

export type EmpleadoMinAggregateInputType = {
  id?: true
  nombre?: true
  id_empresa?: true
  apellido?: true
}

export type EmpleadoMaxAggregateInputType = {
  id?: true
  nombre?: true
  id_empresa?: true
  apellido?: true
}

export type EmpleadoCountAggregateInputType = {
  id?: true
  nombre?: true
  id_empresa?: true
  apellido?: true
  _all?: true
}

export type EmpleadoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which empleado to aggregate.
   */
  where?: Prisma.empleadoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empleados to fetch.
   */
  orderBy?: Prisma.empleadoOrderByWithRelationInput | Prisma.empleadoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.empleadoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empleados from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empleados.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned empleados
  **/
  _count?: true | EmpleadoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmpleadoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmpleadoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmpleadoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmpleadoMaxAggregateInputType
}

export type GetEmpleadoAggregateType<T extends EmpleadoAggregateArgs> = {
      [P in keyof T & keyof AggregateEmpleado]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmpleado[P]>
    : Prisma.GetScalarType<T[P], AggregateEmpleado[P]>
}




export type empleadoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.empleadoWhereInput
  orderBy?: Prisma.empleadoOrderByWithAggregationInput | Prisma.empleadoOrderByWithAggregationInput[]
  by: Prisma.EmpleadoScalarFieldEnum[] | Prisma.EmpleadoScalarFieldEnum
  having?: Prisma.empleadoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmpleadoCountAggregateInputType | true
  _avg?: EmpleadoAvgAggregateInputType
  _sum?: EmpleadoSumAggregateInputType
  _min?: EmpleadoMinAggregateInputType
  _max?: EmpleadoMaxAggregateInputType
}

export type EmpleadoGroupByOutputType = {
  id: number
  nombre: string
  id_empresa: number | null
  apellido: string | null
  _count: EmpleadoCountAggregateOutputType | null
  _avg: EmpleadoAvgAggregateOutputType | null
  _sum: EmpleadoSumAggregateOutputType | null
  _min: EmpleadoMinAggregateOutputType | null
  _max: EmpleadoMaxAggregateOutputType | null
}

export type GetEmpleadoGroupByPayload<T extends empleadoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmpleadoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmpleadoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmpleadoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmpleadoGroupByOutputType[P]>
      }
    >
  >



export type empleadoWhereInput = {
  AND?: Prisma.empleadoWhereInput | Prisma.empleadoWhereInput[]
  OR?: Prisma.empleadoWhereInput[]
  NOT?: Prisma.empleadoWhereInput | Prisma.empleadoWhereInput[]
  id?: Prisma.IntFilter<"empleado"> | number
  nombre?: Prisma.StringFilter<"empleado"> | string
  id_empresa?: Prisma.IntNullableFilter<"empleado"> | number | null
  apellido?: Prisma.StringNullableFilter<"empleado"> | string | null
  empresa?: Prisma.XOR<Prisma.EmpresaNullableScalarRelationFilter, Prisma.empresaWhereInput> | null
}

export type empleadoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  id_empresa?: Prisma.SortOrderInput | Prisma.SortOrder
  apellido?: Prisma.SortOrderInput | Prisma.SortOrder
  empresa?: Prisma.empresaOrderByWithRelationInput
}

export type empleadoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.empleadoWhereInput | Prisma.empleadoWhereInput[]
  OR?: Prisma.empleadoWhereInput[]
  NOT?: Prisma.empleadoWhereInput | Prisma.empleadoWhereInput[]
  nombre?: Prisma.StringFilter<"empleado"> | string
  id_empresa?: Prisma.IntNullableFilter<"empleado"> | number | null
  apellido?: Prisma.StringNullableFilter<"empleado"> | string | null
  empresa?: Prisma.XOR<Prisma.EmpresaNullableScalarRelationFilter, Prisma.empresaWhereInput> | null
}, "id">

export type empleadoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  id_empresa?: Prisma.SortOrderInput | Prisma.SortOrder
  apellido?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.empleadoCountOrderByAggregateInput
  _avg?: Prisma.empleadoAvgOrderByAggregateInput
  _max?: Prisma.empleadoMaxOrderByAggregateInput
  _min?: Prisma.empleadoMinOrderByAggregateInput
  _sum?: Prisma.empleadoSumOrderByAggregateInput
}

export type empleadoScalarWhereWithAggregatesInput = {
  AND?: Prisma.empleadoScalarWhereWithAggregatesInput | Prisma.empleadoScalarWhereWithAggregatesInput[]
  OR?: Prisma.empleadoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.empleadoScalarWhereWithAggregatesInput | Prisma.empleadoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"empleado"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"empleado"> | string
  id_empresa?: Prisma.IntNullableWithAggregatesFilter<"empleado"> | number | null
  apellido?: Prisma.StringNullableWithAggregatesFilter<"empleado"> | string | null
}

export type empleadoCreateInput = {
  nombre: string
  apellido?: string | null
  empresa?: Prisma.empresaCreateNestedOneWithoutEmpleadoInput
}

export type empleadoUncheckedCreateInput = {
  id?: number
  nombre: string
  id_empresa?: number | null
  apellido?: string | null
}

export type empleadoUpdateInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  apellido?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  empresa?: Prisma.empresaUpdateOneWithoutEmpleadoNestedInput
}

export type empleadoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  id_empresa?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  apellido?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type empleadoCreateManyInput = {
  id?: number
  nombre: string
  id_empresa?: number | null
  apellido?: string | null
}

export type empleadoUpdateManyMutationInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  apellido?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type empleadoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  id_empresa?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  apellido?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type empleadoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  id_empresa?: Prisma.SortOrder
  apellido?: Prisma.SortOrder
}

export type empleadoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_empresa?: Prisma.SortOrder
}

export type empleadoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  id_empresa?: Prisma.SortOrder
  apellido?: Prisma.SortOrder
}

export type empleadoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  id_empresa?: Prisma.SortOrder
  apellido?: Prisma.SortOrder
}

export type empleadoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_empresa?: Prisma.SortOrder
}

export type EmpleadoListRelationFilter = {
  every?: Prisma.empleadoWhereInput
  some?: Prisma.empleadoWhereInput
  none?: Prisma.empleadoWhereInput
}

export type empleadoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type empleadoCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.empleadoCreateWithoutEmpresaInput, Prisma.empleadoUncheckedCreateWithoutEmpresaInput> | Prisma.empleadoCreateWithoutEmpresaInput[] | Prisma.empleadoUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.empleadoCreateOrConnectWithoutEmpresaInput | Prisma.empleadoCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.empleadoCreateManyEmpresaInputEnvelope
  connect?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
}

export type empleadoUncheckedCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.empleadoCreateWithoutEmpresaInput, Prisma.empleadoUncheckedCreateWithoutEmpresaInput> | Prisma.empleadoCreateWithoutEmpresaInput[] | Prisma.empleadoUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.empleadoCreateOrConnectWithoutEmpresaInput | Prisma.empleadoCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.empleadoCreateManyEmpresaInputEnvelope
  connect?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
}

export type empleadoUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.empleadoCreateWithoutEmpresaInput, Prisma.empleadoUncheckedCreateWithoutEmpresaInput> | Prisma.empleadoCreateWithoutEmpresaInput[] | Prisma.empleadoUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.empleadoCreateOrConnectWithoutEmpresaInput | Prisma.empleadoCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.empleadoUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.empleadoUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.empleadoCreateManyEmpresaInputEnvelope
  set?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  disconnect?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  delete?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  connect?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  update?: Prisma.empleadoUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.empleadoUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.empleadoUpdateManyWithWhereWithoutEmpresaInput | Prisma.empleadoUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.empleadoScalarWhereInput | Prisma.empleadoScalarWhereInput[]
}

export type empleadoUncheckedUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.empleadoCreateWithoutEmpresaInput, Prisma.empleadoUncheckedCreateWithoutEmpresaInput> | Prisma.empleadoCreateWithoutEmpresaInput[] | Prisma.empleadoUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.empleadoCreateOrConnectWithoutEmpresaInput | Prisma.empleadoCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.empleadoUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.empleadoUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.empleadoCreateManyEmpresaInputEnvelope
  set?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  disconnect?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  delete?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  connect?: Prisma.empleadoWhereUniqueInput | Prisma.empleadoWhereUniqueInput[]
  update?: Prisma.empleadoUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.empleadoUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.empleadoUpdateManyWithWhereWithoutEmpresaInput | Prisma.empleadoUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.empleadoScalarWhereInput | Prisma.empleadoScalarWhereInput[]
}

export type empleadoCreateWithoutEmpresaInput = {
  nombre: string
  apellido?: string | null
}

export type empleadoUncheckedCreateWithoutEmpresaInput = {
  id?: number
  nombre: string
  apellido?: string | null
}

export type empleadoCreateOrConnectWithoutEmpresaInput = {
  where: Prisma.empleadoWhereUniqueInput
  create: Prisma.XOR<Prisma.empleadoCreateWithoutEmpresaInput, Prisma.empleadoUncheckedCreateWithoutEmpresaInput>
}

export type empleadoCreateManyEmpresaInputEnvelope = {
  data: Prisma.empleadoCreateManyEmpresaInput | Prisma.empleadoCreateManyEmpresaInput[]
  skipDuplicates?: boolean
}

export type empleadoUpsertWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.empleadoWhereUniqueInput
  update: Prisma.XOR<Prisma.empleadoUpdateWithoutEmpresaInput, Prisma.empleadoUncheckedUpdateWithoutEmpresaInput>
  create: Prisma.XOR<Prisma.empleadoCreateWithoutEmpresaInput, Prisma.empleadoUncheckedCreateWithoutEmpresaInput>
}

export type empleadoUpdateWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.empleadoWhereUniqueInput
  data: Prisma.XOR<Prisma.empleadoUpdateWithoutEmpresaInput, Prisma.empleadoUncheckedUpdateWithoutEmpresaInput>
}

export type empleadoUpdateManyWithWhereWithoutEmpresaInput = {
  where: Prisma.empleadoScalarWhereInput
  data: Prisma.XOR<Prisma.empleadoUpdateManyMutationInput, Prisma.empleadoUncheckedUpdateManyWithoutEmpresaInput>
}

export type empleadoScalarWhereInput = {
  AND?: Prisma.empleadoScalarWhereInput | Prisma.empleadoScalarWhereInput[]
  OR?: Prisma.empleadoScalarWhereInput[]
  NOT?: Prisma.empleadoScalarWhereInput | Prisma.empleadoScalarWhereInput[]
  id?: Prisma.IntFilter<"empleado"> | number
  nombre?: Prisma.StringFilter<"empleado"> | string
  id_empresa?: Prisma.IntNullableFilter<"empleado"> | number | null
  apellido?: Prisma.StringNullableFilter<"empleado"> | string | null
}

export type empleadoCreateManyEmpresaInput = {
  id?: number
  nombre: string
  apellido?: string | null
}

export type empleadoUpdateWithoutEmpresaInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  apellido?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type empleadoUncheckedUpdateWithoutEmpresaInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  apellido?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type empleadoUncheckedUpdateManyWithoutEmpresaInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  apellido?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type empleadoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  id_empresa?: boolean
  apellido?: boolean
  empresa?: boolean | Prisma.empleado$empresaArgs<ExtArgs>
}, ExtArgs["result"]["empleado"]>

export type empleadoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  id_empresa?: boolean
  apellido?: boolean
  empresa?: boolean | Prisma.empleado$empresaArgs<ExtArgs>
}, ExtArgs["result"]["empleado"]>

export type empleadoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  id_empresa?: boolean
  apellido?: boolean
  empresa?: boolean | Prisma.empleado$empresaArgs<ExtArgs>
}, ExtArgs["result"]["empleado"]>

export type empleadoSelectScalar = {
  id?: boolean
  nombre?: boolean
  id_empresa?: boolean
  apellido?: boolean
}

export type empleadoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nombre" | "id_empresa" | "apellido", ExtArgs["result"]["empleado"]>
export type empleadoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.empleado$empresaArgs<ExtArgs>
}
export type empleadoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.empleado$empresaArgs<ExtArgs>
}
export type empleadoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.empleado$empresaArgs<ExtArgs>
}

export type $empleadoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "empleado"
  objects: {
    empresa: Prisma.$empresaPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nombre: string
    id_empresa: number | null
    apellido: string | null
  }, ExtArgs["result"]["empleado"]>
  composites: {}
}

export type empleadoGetPayload<S extends boolean | null | undefined | empleadoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$empleadoPayload, S>

export type empleadoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<empleadoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmpleadoCountAggregateInputType | true
  }

export interface empleadoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['empleado'], meta: { name: 'empleado' } }
  /**
   * Find zero or one Empleado that matches the filter.
   * @param {empleadoFindUniqueArgs} args - Arguments to find a Empleado
   * @example
   * // Get one Empleado
   * const empleado = await prisma.empleado.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends empleadoFindUniqueArgs>(args: Prisma.SelectSubset<T, empleadoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Empleado that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {empleadoFindUniqueOrThrowArgs} args - Arguments to find a Empleado
   * @example
   * // Get one Empleado
   * const empleado = await prisma.empleado.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends empleadoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, empleadoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empleado that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empleadoFindFirstArgs} args - Arguments to find a Empleado
   * @example
   * // Get one Empleado
   * const empleado = await prisma.empleado.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends empleadoFindFirstArgs>(args?: Prisma.SelectSubset<T, empleadoFindFirstArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empleado that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empleadoFindFirstOrThrowArgs} args - Arguments to find a Empleado
   * @example
   * // Get one Empleado
   * const empleado = await prisma.empleado.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends empleadoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, empleadoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Empleados that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empleadoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Empleados
   * const empleados = await prisma.empleado.findMany()
   * 
   * // Get first 10 Empleados
   * const empleados = await prisma.empleado.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const empleadoWithIdOnly = await prisma.empleado.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends empleadoFindManyArgs>(args?: Prisma.SelectSubset<T, empleadoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Empleado.
   * @param {empleadoCreateArgs} args - Arguments to create a Empleado.
   * @example
   * // Create one Empleado
   * const Empleado = await prisma.empleado.create({
   *   data: {
   *     // ... data to create a Empleado
   *   }
   * })
   * 
   */
  create<T extends empleadoCreateArgs>(args: Prisma.SelectSubset<T, empleadoCreateArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Empleados.
   * @param {empleadoCreateManyArgs} args - Arguments to create many Empleados.
   * @example
   * // Create many Empleados
   * const empleado = await prisma.empleado.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends empleadoCreateManyArgs>(args?: Prisma.SelectSubset<T, empleadoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Empleados and returns the data saved in the database.
   * @param {empleadoCreateManyAndReturnArgs} args - Arguments to create many Empleados.
   * @example
   * // Create many Empleados
   * const empleado = await prisma.empleado.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Empleados and only return the `id`
   * const empleadoWithIdOnly = await prisma.empleado.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends empleadoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, empleadoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Empleado.
   * @param {empleadoDeleteArgs} args - Arguments to delete one Empleado.
   * @example
   * // Delete one Empleado
   * const Empleado = await prisma.empleado.delete({
   *   where: {
   *     // ... filter to delete one Empleado
   *   }
   * })
   * 
   */
  delete<T extends empleadoDeleteArgs>(args: Prisma.SelectSubset<T, empleadoDeleteArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Empleado.
   * @param {empleadoUpdateArgs} args - Arguments to update one Empleado.
   * @example
   * // Update one Empleado
   * const empleado = await prisma.empleado.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends empleadoUpdateArgs>(args: Prisma.SelectSubset<T, empleadoUpdateArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Empleados.
   * @param {empleadoDeleteManyArgs} args - Arguments to filter Empleados to delete.
   * @example
   * // Delete a few Empleados
   * const { count } = await prisma.empleado.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends empleadoDeleteManyArgs>(args?: Prisma.SelectSubset<T, empleadoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empleados.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empleadoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Empleados
   * const empleado = await prisma.empleado.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends empleadoUpdateManyArgs>(args: Prisma.SelectSubset<T, empleadoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empleados and returns the data updated in the database.
   * @param {empleadoUpdateManyAndReturnArgs} args - Arguments to update many Empleados.
   * @example
   * // Update many Empleados
   * const empleado = await prisma.empleado.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Empleados and only return the `id`
   * const empleadoWithIdOnly = await prisma.empleado.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends empleadoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, empleadoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Empleado.
   * @param {empleadoUpsertArgs} args - Arguments to update or create a Empleado.
   * @example
   * // Update or create a Empleado
   * const empleado = await prisma.empleado.upsert({
   *   create: {
   *     // ... data to create a Empleado
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Empleado we want to update
   *   }
   * })
   */
  upsert<T extends empleadoUpsertArgs>(args: Prisma.SelectSubset<T, empleadoUpsertArgs<ExtArgs>>): Prisma.Prisma__empleadoClient<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Empleados.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empleadoCountArgs} args - Arguments to filter Empleados to count.
   * @example
   * // Count the number of Empleados
   * const count = await prisma.empleado.count({
   *   where: {
   *     // ... the filter for the Empleados we want to count
   *   }
   * })
  **/
  count<T extends empleadoCountArgs>(
    args?: Prisma.Subset<T, empleadoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmpleadoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Empleado.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpleadoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmpleadoAggregateArgs>(args: Prisma.Subset<T, EmpleadoAggregateArgs>): Prisma.PrismaPromise<GetEmpleadoAggregateType<T>>

  /**
   * Group by Empleado.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empleadoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends empleadoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: empleadoGroupByArgs['orderBy'] }
      : { orderBy?: empleadoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, empleadoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmpleadoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the empleado model
 */
readonly fields: empleadoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for empleado.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__empleadoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  empresa<T extends Prisma.empleado$empresaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.empleado$empresaArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the empleado model
 */
export interface empleadoFieldRefs {
  readonly id: Prisma.FieldRef<"empleado", 'Int'>
  readonly nombre: Prisma.FieldRef<"empleado", 'String'>
  readonly id_empresa: Prisma.FieldRef<"empleado", 'Int'>
  readonly apellido: Prisma.FieldRef<"empleado", 'String'>
}
    

// Custom InputTypes
/**
 * empleado findUnique
 */
export type empleadoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * Filter, which empleado to fetch.
   */
  where: Prisma.empleadoWhereUniqueInput
}

/**
 * empleado findUniqueOrThrow
 */
export type empleadoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * Filter, which empleado to fetch.
   */
  where: Prisma.empleadoWhereUniqueInput
}

/**
 * empleado findFirst
 */
export type empleadoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * Filter, which empleado to fetch.
   */
  where?: Prisma.empleadoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empleados to fetch.
   */
  orderBy?: Prisma.empleadoOrderByWithRelationInput | Prisma.empleadoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for empleados.
   */
  cursor?: Prisma.empleadoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empleados from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empleados.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of empleados.
   */
  distinct?: Prisma.EmpleadoScalarFieldEnum | Prisma.EmpleadoScalarFieldEnum[]
}

/**
 * empleado findFirstOrThrow
 */
export type empleadoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * Filter, which empleado to fetch.
   */
  where?: Prisma.empleadoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empleados to fetch.
   */
  orderBy?: Prisma.empleadoOrderByWithRelationInput | Prisma.empleadoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for empleados.
   */
  cursor?: Prisma.empleadoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empleados from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empleados.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of empleados.
   */
  distinct?: Prisma.EmpleadoScalarFieldEnum | Prisma.EmpleadoScalarFieldEnum[]
}

/**
 * empleado findMany
 */
export type empleadoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * Filter, which empleados to fetch.
   */
  where?: Prisma.empleadoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empleados to fetch.
   */
  orderBy?: Prisma.empleadoOrderByWithRelationInput | Prisma.empleadoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing empleados.
   */
  cursor?: Prisma.empleadoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empleados from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empleados.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of empleados.
   */
  distinct?: Prisma.EmpleadoScalarFieldEnum | Prisma.EmpleadoScalarFieldEnum[]
}

/**
 * empleado create
 */
export type empleadoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * The data needed to create a empleado.
   */
  data: Prisma.XOR<Prisma.empleadoCreateInput, Prisma.empleadoUncheckedCreateInput>
}

/**
 * empleado createMany
 */
export type empleadoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many empleados.
   */
  data: Prisma.empleadoCreateManyInput | Prisma.empleadoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * empleado createManyAndReturn
 */
export type empleadoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * The data used to create many empleados.
   */
  data: Prisma.empleadoCreateManyInput | Prisma.empleadoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * empleado update
 */
export type empleadoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * The data needed to update a empleado.
   */
  data: Prisma.XOR<Prisma.empleadoUpdateInput, Prisma.empleadoUncheckedUpdateInput>
  /**
   * Choose, which empleado to update.
   */
  where: Prisma.empleadoWhereUniqueInput
}

/**
 * empleado updateMany
 */
export type empleadoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update empleados.
   */
  data: Prisma.XOR<Prisma.empleadoUpdateManyMutationInput, Prisma.empleadoUncheckedUpdateManyInput>
  /**
   * Filter which empleados to update
   */
  where?: Prisma.empleadoWhereInput
  /**
   * Limit how many empleados to update.
   */
  limit?: number
}

/**
 * empleado updateManyAndReturn
 */
export type empleadoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * The data used to update empleados.
   */
  data: Prisma.XOR<Prisma.empleadoUpdateManyMutationInput, Prisma.empleadoUncheckedUpdateManyInput>
  /**
   * Filter which empleados to update
   */
  where?: Prisma.empleadoWhereInput
  /**
   * Limit how many empleados to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * empleado upsert
 */
export type empleadoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * The filter to search for the empleado to update in case it exists.
   */
  where: Prisma.empleadoWhereUniqueInput
  /**
   * In case the empleado found by the `where` argument doesn't exist, create a new empleado with this data.
   */
  create: Prisma.XOR<Prisma.empleadoCreateInput, Prisma.empleadoUncheckedCreateInput>
  /**
   * In case the empleado was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.empleadoUpdateInput, Prisma.empleadoUncheckedUpdateInput>
}

/**
 * empleado delete
 */
export type empleadoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  /**
   * Filter which empleado to delete.
   */
  where: Prisma.empleadoWhereUniqueInput
}

/**
 * empleado deleteMany
 */
export type empleadoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which empleados to delete
   */
  where?: Prisma.empleadoWhereInput
  /**
   * Limit how many empleados to delete.
   */
  limit?: number
}

/**
 * empleado.empresa
 */
export type empleado$empresaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  where?: Prisma.empresaWhereInput
}

/**
 * empleado without action
 */
export type empleadoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
}
