
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `empresa` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model empresa
 * 
 */
export type empresaModel = runtime.Types.Result.DefaultSelection<Prisma.$empresaPayload>

export type AggregateEmpresa = {
  _count: EmpresaCountAggregateOutputType | null
  _avg: EmpresaAvgAggregateOutputType | null
  _sum: EmpresaSumAggregateOutputType | null
  _min: EmpresaMinAggregateOutputType | null
  _max: EmpresaMaxAggregateOutputType | null
}

export type EmpresaAvgAggregateOutputType = {
  id: number | null
}

export type EmpresaSumAggregateOutputType = {
  id: number | null
}

export type EmpresaMinAggregateOutputType = {
  id: number | null
  nombre: string | null
}

export type EmpresaMaxAggregateOutputType = {
  id: number | null
  nombre: string | null
}

export type EmpresaCountAggregateOutputType = {
  id: number
  nombre: number
  _all: number
}


export type EmpresaAvgAggregateInputType = {
  id?: true
}

export type EmpresaSumAggregateInputType = {
  id?: true
}

export type EmpresaMinAggregateInputType = {
  id?: true
  nombre?: true
}

export type EmpresaMaxAggregateInputType = {
  id?: true
  nombre?: true
}

export type EmpresaCountAggregateInputType = {
  id?: true
  nombre?: true
  _all?: true
}

export type EmpresaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which empresa to aggregate.
   */
  where?: Prisma.empresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empresas to fetch.
   */
  orderBy?: Prisma.empresaOrderByWithRelationInput | Prisma.empresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.empresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned empresas
  **/
  _count?: true | EmpresaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmpresaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmpresaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmpresaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmpresaMaxAggregateInputType
}

export type GetEmpresaAggregateType<T extends EmpresaAggregateArgs> = {
      [P in keyof T & keyof AggregateEmpresa]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmpresa[P]>
    : Prisma.GetScalarType<T[P], AggregateEmpresa[P]>
}




export type empresaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.empresaWhereInput
  orderBy?: Prisma.empresaOrderByWithAggregationInput | Prisma.empresaOrderByWithAggregationInput[]
  by: Prisma.EmpresaScalarFieldEnum[] | Prisma.EmpresaScalarFieldEnum
  having?: Prisma.empresaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmpresaCountAggregateInputType | true
  _avg?: EmpresaAvgAggregateInputType
  _sum?: EmpresaSumAggregateInputType
  _min?: EmpresaMinAggregateInputType
  _max?: EmpresaMaxAggregateInputType
}

export type EmpresaGroupByOutputType = {
  id: number
  nombre: string
  _count: EmpresaCountAggregateOutputType | null
  _avg: EmpresaAvgAggregateOutputType | null
  _sum: EmpresaSumAggregateOutputType | null
  _min: EmpresaMinAggregateOutputType | null
  _max: EmpresaMaxAggregateOutputType | null
}

export type GetEmpresaGroupByPayload<T extends empresaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmpresaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmpresaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmpresaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmpresaGroupByOutputType[P]>
      }
    >
  >



export type empresaWhereInput = {
  AND?: Prisma.empresaWhereInput | Prisma.empresaWhereInput[]
  OR?: Prisma.empresaWhereInput[]
  NOT?: Prisma.empresaWhereInput | Prisma.empresaWhereInput[]
  id?: Prisma.IntFilter<"empresa"> | number
  nombre?: Prisma.StringFilter<"empresa"> | string
  empleado?: Prisma.EmpleadoListRelationFilter
}

export type empresaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  empleado?: Prisma.empleadoOrderByRelationAggregateInput
}

export type empresaWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.empresaWhereInput | Prisma.empresaWhereInput[]
  OR?: Prisma.empresaWhereInput[]
  NOT?: Prisma.empresaWhereInput | Prisma.empresaWhereInput[]
  nombre?: Prisma.StringFilter<"empresa"> | string
  empleado?: Prisma.EmpleadoListRelationFilter
}, "id">

export type empresaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  _count?: Prisma.empresaCountOrderByAggregateInput
  _avg?: Prisma.empresaAvgOrderByAggregateInput
  _max?: Prisma.empresaMaxOrderByAggregateInput
  _min?: Prisma.empresaMinOrderByAggregateInput
  _sum?: Prisma.empresaSumOrderByAggregateInput
}

export type empresaScalarWhereWithAggregatesInput = {
  AND?: Prisma.empresaScalarWhereWithAggregatesInput | Prisma.empresaScalarWhereWithAggregatesInput[]
  OR?: Prisma.empresaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.empresaScalarWhereWithAggregatesInput | Prisma.empresaScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"empresa"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"empresa"> | string
}

export type empresaCreateInput = {
  nombre: string
  empleado?: Prisma.empleadoCreateNestedManyWithoutEmpresaInput
}

export type empresaUncheckedCreateInput = {
  id?: number
  nombre: string
  empleado?: Prisma.empleadoUncheckedCreateNestedManyWithoutEmpresaInput
}

export type empresaUpdateInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  empleado?: Prisma.empleadoUpdateManyWithoutEmpresaNestedInput
}

export type empresaUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  empleado?: Prisma.empleadoUncheckedUpdateManyWithoutEmpresaNestedInput
}

export type empresaCreateManyInput = {
  id?: number
  nombre: string
}

export type empresaUpdateManyMutationInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
}

export type empresaUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EmpresaNullableScalarRelationFilter = {
  is?: Prisma.empresaWhereInput | null
  isNot?: Prisma.empresaWhereInput | null
}

export type empresaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
}

export type empresaAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type empresaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
}

export type empresaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
}

export type empresaSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type empresaCreateNestedOneWithoutEmpleadoInput = {
  create?: Prisma.XOR<Prisma.empresaCreateWithoutEmpleadoInput, Prisma.empresaUncheckedCreateWithoutEmpleadoInput>
  connectOrCreate?: Prisma.empresaCreateOrConnectWithoutEmpleadoInput
  connect?: Prisma.empresaWhereUniqueInput
}

export type empresaUpdateOneWithoutEmpleadoNestedInput = {
  create?: Prisma.XOR<Prisma.empresaCreateWithoutEmpleadoInput, Prisma.empresaUncheckedCreateWithoutEmpleadoInput>
  connectOrCreate?: Prisma.empresaCreateOrConnectWithoutEmpleadoInput
  upsert?: Prisma.empresaUpsertWithoutEmpleadoInput
  disconnect?: Prisma.empresaWhereInput | boolean
  delete?: Prisma.empresaWhereInput | boolean
  connect?: Prisma.empresaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.empresaUpdateToOneWithWhereWithoutEmpleadoInput, Prisma.empresaUpdateWithoutEmpleadoInput>, Prisma.empresaUncheckedUpdateWithoutEmpleadoInput>
}

export type empresaCreateWithoutEmpleadoInput = {
  nombre: string
}

export type empresaUncheckedCreateWithoutEmpleadoInput = {
  id?: number
  nombre: string
}

export type empresaCreateOrConnectWithoutEmpleadoInput = {
  where: Prisma.empresaWhereUniqueInput
  create: Prisma.XOR<Prisma.empresaCreateWithoutEmpleadoInput, Prisma.empresaUncheckedCreateWithoutEmpleadoInput>
}

export type empresaUpsertWithoutEmpleadoInput = {
  update: Prisma.XOR<Prisma.empresaUpdateWithoutEmpleadoInput, Prisma.empresaUncheckedUpdateWithoutEmpleadoInput>
  create: Prisma.XOR<Prisma.empresaCreateWithoutEmpleadoInput, Prisma.empresaUncheckedCreateWithoutEmpleadoInput>
  where?: Prisma.empresaWhereInput
}

export type empresaUpdateToOneWithWhereWithoutEmpleadoInput = {
  where?: Prisma.empresaWhereInput
  data: Prisma.XOR<Prisma.empresaUpdateWithoutEmpleadoInput, Prisma.empresaUncheckedUpdateWithoutEmpleadoInput>
}

export type empresaUpdateWithoutEmpleadoInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
}

export type empresaUncheckedUpdateWithoutEmpleadoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type EmpresaCountOutputType
 */

export type EmpresaCountOutputType = {
  empleado: number
}

export type EmpresaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empleado?: boolean | EmpresaCountOutputTypeCountEmpleadoArgs
}

/**
 * EmpresaCountOutputType without action
 */
export type EmpresaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmpresaCountOutputType
   */
  select?: Prisma.EmpresaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmpresaCountOutputType without action
 */
export type EmpresaCountOutputTypeCountEmpleadoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.empleadoWhereInput
}


export type empresaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  empleado?: boolean | Prisma.empresa$empleadoArgs<ExtArgs>
  _count?: boolean | Prisma.EmpresaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["empresa"]>

export type empresaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
}, ExtArgs["result"]["empresa"]>

export type empresaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
}, ExtArgs["result"]["empresa"]>

export type empresaSelectScalar = {
  id?: boolean
  nombre?: boolean
}

export type empresaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nombre", ExtArgs["result"]["empresa"]>
export type empresaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empleado?: boolean | Prisma.empresa$empleadoArgs<ExtArgs>
  _count?: boolean | Prisma.EmpresaCountOutputTypeDefaultArgs<ExtArgs>
}
export type empresaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type empresaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $empresaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "empresa"
  objects: {
    empleado: Prisma.$empleadoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nombre: string
  }, ExtArgs["result"]["empresa"]>
  composites: {}
}

export type empresaGetPayload<S extends boolean | null | undefined | empresaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$empresaPayload, S>

export type empresaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<empresaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmpresaCountAggregateInputType | true
  }

export interface empresaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['empresa'], meta: { name: 'empresa' } }
  /**
   * Find zero or one Empresa that matches the filter.
   * @param {empresaFindUniqueArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends empresaFindUniqueArgs>(args: Prisma.SelectSubset<T, empresaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Empresa that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {empresaFindUniqueOrThrowArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends empresaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, empresaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empresa that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empresaFindFirstArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends empresaFindFirstArgs>(args?: Prisma.SelectSubset<T, empresaFindFirstArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empresa that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empresaFindFirstOrThrowArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends empresaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, empresaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Empresas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empresaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Empresas
   * const empresas = await prisma.empresa.findMany()
   * 
   * // Get first 10 Empresas
   * const empresas = await prisma.empresa.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const empresaWithIdOnly = await prisma.empresa.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends empresaFindManyArgs>(args?: Prisma.SelectSubset<T, empresaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Empresa.
   * @param {empresaCreateArgs} args - Arguments to create a Empresa.
   * @example
   * // Create one Empresa
   * const Empresa = await prisma.empresa.create({
   *   data: {
   *     // ... data to create a Empresa
   *   }
   * })
   * 
   */
  create<T extends empresaCreateArgs>(args: Prisma.SelectSubset<T, empresaCreateArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Empresas.
   * @param {empresaCreateManyArgs} args - Arguments to create many Empresas.
   * @example
   * // Create many Empresas
   * const empresa = await prisma.empresa.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends empresaCreateManyArgs>(args?: Prisma.SelectSubset<T, empresaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Empresas and returns the data saved in the database.
   * @param {empresaCreateManyAndReturnArgs} args - Arguments to create many Empresas.
   * @example
   * // Create many Empresas
   * const empresa = await prisma.empresa.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Empresas and only return the `id`
   * const empresaWithIdOnly = await prisma.empresa.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends empresaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, empresaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Empresa.
   * @param {empresaDeleteArgs} args - Arguments to delete one Empresa.
   * @example
   * // Delete one Empresa
   * const Empresa = await prisma.empresa.delete({
   *   where: {
   *     // ... filter to delete one Empresa
   *   }
   * })
   * 
   */
  delete<T extends empresaDeleteArgs>(args: Prisma.SelectSubset<T, empresaDeleteArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Empresa.
   * @param {empresaUpdateArgs} args - Arguments to update one Empresa.
   * @example
   * // Update one Empresa
   * const empresa = await prisma.empresa.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends empresaUpdateArgs>(args: Prisma.SelectSubset<T, empresaUpdateArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Empresas.
   * @param {empresaDeleteManyArgs} args - Arguments to filter Empresas to delete.
   * @example
   * // Delete a few Empresas
   * const { count } = await prisma.empresa.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends empresaDeleteManyArgs>(args?: Prisma.SelectSubset<T, empresaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empresaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Empresas
   * const empresa = await prisma.empresa.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends empresaUpdateManyArgs>(args: Prisma.SelectSubset<T, empresaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empresas and returns the data updated in the database.
   * @param {empresaUpdateManyAndReturnArgs} args - Arguments to update many Empresas.
   * @example
   * // Update many Empresas
   * const empresa = await prisma.empresa.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Empresas and only return the `id`
   * const empresaWithIdOnly = await prisma.empresa.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends empresaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, empresaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Empresa.
   * @param {empresaUpsertArgs} args - Arguments to update or create a Empresa.
   * @example
   * // Update or create a Empresa
   * const empresa = await prisma.empresa.upsert({
   *   create: {
   *     // ... data to create a Empresa
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Empresa we want to update
   *   }
   * })
   */
  upsert<T extends empresaUpsertArgs>(args: Prisma.SelectSubset<T, empresaUpsertArgs<ExtArgs>>): Prisma.Prisma__empresaClient<runtime.Types.Result.GetResult<Prisma.$empresaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empresaCountArgs} args - Arguments to filter Empresas to count.
   * @example
   * // Count the number of Empresas
   * const count = await prisma.empresa.count({
   *   where: {
   *     // ... the filter for the Empresas we want to count
   *   }
   * })
  **/
  count<T extends empresaCountArgs>(
    args?: Prisma.Subset<T, empresaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmpresaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Empresa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmpresaAggregateArgs>(args: Prisma.Subset<T, EmpresaAggregateArgs>): Prisma.PrismaPromise<GetEmpresaAggregateType<T>>

  /**
   * Group by Empresa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {empresaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends empresaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: empresaGroupByArgs['orderBy'] }
      : { orderBy?: empresaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, empresaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmpresaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the empresa model
 */
readonly fields: empresaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for empresa.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__empresaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  empleado<T extends Prisma.empresa$empleadoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.empresa$empleadoArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$empleadoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the empresa model
 */
export interface empresaFieldRefs {
  readonly id: Prisma.FieldRef<"empresa", 'Int'>
  readonly nombre: Prisma.FieldRef<"empresa", 'String'>
}
    

// Custom InputTypes
/**
 * empresa findUnique
 */
export type empresaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * Filter, which empresa to fetch.
   */
  where: Prisma.empresaWhereUniqueInput
}

/**
 * empresa findUniqueOrThrow
 */
export type empresaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * Filter, which empresa to fetch.
   */
  where: Prisma.empresaWhereUniqueInput
}

/**
 * empresa findFirst
 */
export type empresaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * Filter, which empresa to fetch.
   */
  where?: Prisma.empresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empresas to fetch.
   */
  orderBy?: Prisma.empresaOrderByWithRelationInput | Prisma.empresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for empresas.
   */
  cursor?: Prisma.empresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of empresas.
   */
  distinct?: Prisma.EmpresaScalarFieldEnum | Prisma.EmpresaScalarFieldEnum[]
}

/**
 * empresa findFirstOrThrow
 */
export type empresaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * Filter, which empresa to fetch.
   */
  where?: Prisma.empresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empresas to fetch.
   */
  orderBy?: Prisma.empresaOrderByWithRelationInput | Prisma.empresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for empresas.
   */
  cursor?: Prisma.empresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of empresas.
   */
  distinct?: Prisma.EmpresaScalarFieldEnum | Prisma.EmpresaScalarFieldEnum[]
}

/**
 * empresa findMany
 */
export type empresaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * Filter, which empresas to fetch.
   */
  where?: Prisma.empresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of empresas to fetch.
   */
  orderBy?: Prisma.empresaOrderByWithRelationInput | Prisma.empresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing empresas.
   */
  cursor?: Prisma.empresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of empresas.
   */
  distinct?: Prisma.EmpresaScalarFieldEnum | Prisma.EmpresaScalarFieldEnum[]
}

/**
 * empresa create
 */
export type empresaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * The data needed to create a empresa.
   */
  data: Prisma.XOR<Prisma.empresaCreateInput, Prisma.empresaUncheckedCreateInput>
}

/**
 * empresa createMany
 */
export type empresaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many empresas.
   */
  data: Prisma.empresaCreateManyInput | Prisma.empresaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * empresa createManyAndReturn
 */
export type empresaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * The data used to create many empresas.
   */
  data: Prisma.empresaCreateManyInput | Prisma.empresaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * empresa update
 */
export type empresaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * The data needed to update a empresa.
   */
  data: Prisma.XOR<Prisma.empresaUpdateInput, Prisma.empresaUncheckedUpdateInput>
  /**
   * Choose, which empresa to update.
   */
  where: Prisma.empresaWhereUniqueInput
}

/**
 * empresa updateMany
 */
export type empresaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update empresas.
   */
  data: Prisma.XOR<Prisma.empresaUpdateManyMutationInput, Prisma.empresaUncheckedUpdateManyInput>
  /**
   * Filter which empresas to update
   */
  where?: Prisma.empresaWhereInput
  /**
   * Limit how many empresas to update.
   */
  limit?: number
}

/**
 * empresa updateManyAndReturn
 */
export type empresaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * The data used to update empresas.
   */
  data: Prisma.XOR<Prisma.empresaUpdateManyMutationInput, Prisma.empresaUncheckedUpdateManyInput>
  /**
   * Filter which empresas to update
   */
  where?: Prisma.empresaWhereInput
  /**
   * Limit how many empresas to update.
   */
  limit?: number
}

/**
 * empresa upsert
 */
export type empresaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * The filter to search for the empresa to update in case it exists.
   */
  where: Prisma.empresaWhereUniqueInput
  /**
   * In case the empresa found by the `where` argument doesn't exist, create a new empresa with this data.
   */
  create: Prisma.XOR<Prisma.empresaCreateInput, Prisma.empresaUncheckedCreateInput>
  /**
   * In case the empresa was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.empresaUpdateInput, Prisma.empresaUncheckedUpdateInput>
}

/**
 * empresa delete
 */
export type empresaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
  /**
   * Filter which empresa to delete.
   */
  where: Prisma.empresaWhereUniqueInput
}

/**
 * empresa deleteMany
 */
export type empresaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which empresas to delete
   */
  where?: Prisma.empresaWhereInput
  /**
   * Limit how many empresas to delete.
   */
  limit?: number
}

/**
 * empresa.empleado
 */
export type empresa$empleadoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empleado
   */
  select?: Prisma.empleadoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empleado
   */
  omit?: Prisma.empleadoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empleadoInclude<ExtArgs> | null
  where?: Prisma.empleadoWhereInput
  orderBy?: Prisma.empleadoOrderByWithRelationInput | Prisma.empleadoOrderByWithRelationInput[]
  cursor?: Prisma.empleadoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmpleadoScalarFieldEnum | Prisma.EmpleadoScalarFieldEnum[]
}

/**
 * empresa without action
 */
export type empresaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the empresa
   */
  select?: Prisma.empresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the empresa
   */
  omit?: Prisma.empresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.empresaInclude<ExtArgs> | null
}
